site_name: Test MCP Servers and more

nav:
  - MCP Cases: index.md
  - Implementations: implementations.md
  # - Links: links.md

repo_url: https://github.com/strowk/mcp-cases
repo_name: strowk/mcp-cases

plugins:
  - search
  - tags:
      tags_file: links.md

theme:
  name: material
  custom_dir: overrides

  logo: assets/logo.png
  favicon: assets/favicon.png

  palette:
    primary: indigo
    scheme: slate
  features:
    - navigation.tracking
    - announce.dismiss
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - navigation.indexes
    - search.suggest
    - header.autohide

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

